name: Docker Image CD

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed
jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: pull docker image
      run: sudo docker pull khobu/bank_marketing:latest
    - name: delete old container
      run: sudo docker rm -f bank_marketing_container || true
    - name: run new container
      run: sudo docker run -d -p 5000:5000 --name bank_marketing_container khobu/bank_marketing:latest
