name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWARD: ${{secrets.DOCKER_PASSWARD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWARD
    - name: Build the Docker image
      run: docker build -t bank_marketing .
    - name: tag docker image
      run: docker tag bank_marketing:latest khobu/bank_marketing:latest
    - name: push docker image
      run: docker push khobu/bank_marketing:latest
